/**
 * Mock data for demos and development without backend.
 */

import type {
  Federation,
  WaldurInstance,
  FederationConnection,
  FederationTransaction,
  FederationAlert,
  DashboardStats,
} from './types';

// Sample federations
export const mockFederations: Federation[] = [
  {
    id: 'fed-001',
    name: 'European Research Cloud Federation',
    slug: 'ercf',
    description: 'Federation of European research computing infrastructure providers enabling seamless resource sharing across institutions.',
    logo_url: null,
    public_discovery: true,
    require_approval: true,
    require_tos_acceptance: true,
    allow_auto_join: false,
    terms_of_service: '# Federation Terms of Service\n\nBy joining this federation, you agree to:\n\n1. Share computing resources in good faith\n2. Maintain uptime and availability standards\n3. Report usage accurately\n4. Protect user data according to GDPR',
    admin_email: 'admin@ercf.eu',
    website_url: 'https://ercf.eu',
    tos_url: 'https://ercf.eu/tos',
    tos_version: '1.0',
    status: 'active',
    created_at: '2024-01-15T10:00:00Z',
    instance_count: 5,
    active_connections: 8,
  },
  {
    id: 'fed-002',
    name: 'Nordic HPC Alliance',
    slug: 'nhpca',
    description: 'Collaborative federation of Nordic HPC centers for shared computing resources.',
    logo_url: null,
    public_discovery: true,
    require_approval: true,
    require_tos_acceptance: true,
    allow_auto_join: true,
    terms_of_service: '# Nordic HPC Alliance Terms\n\nMembers must:\n\n- Provide fair-share access to resources\n- Participate in quarterly coordination meetings\n- Maintain API compatibility',
    admin_email: 'contact@nhpca.org',
    website_url: 'https://nhpca.org',
    tos_url: 'https://nhpca.org/terms',
    tos_version: '2.1',
    status: 'active',
    created_at: '2024-03-01T08:00:00Z',
    instance_count: 3,
    active_connections: 4,
  },
];

// Sample Waldur instances
export const mockInstances: WaldurInstance[] = [
  {
    id: 'inst-001',
    federation_id: 'fed-001',
    name: 'CERN Cloud',
    api_url: 'https://cloud.cern.ch/api',
    homepage_url: 'https://cloud.cern.ch',
    uuid: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    version: '6.8.0',
    organization_name: 'CERN',
    country: 'CH',
    description: 'CERN computing cloud providing research computing resources.',
    logo_url: null,
    admin_email: 'cloud-support@cern.ch',
    capabilities: ['remote_customer', 'shared_offerings', 'usage_reporting'],
    tags: ['hpc', 'physics', 'research'],
    status: 'active',
    connection_status: 'online',
    last_seen: '2024-06-15T14:30:00Z',
    tos_accepted: true,
    offering_count: 45,
    customer_count: 120,
    project_count: 350,
    registered_at: '2024-01-20T10:00:00Z',
    joined_at: '2024-01-20T10:30:00Z',
  },
  {
    id: 'inst-002',
    federation_id: 'fed-001',
    name: 'ETH Zurich Research Cloud',
    api_url: 'https://cloud.ethz.ch/api',
    homepage_url: 'https://cloud.ethz.ch',
    uuid: 'b2c3d4e5-f6a7-8901-bcde-f23456789012',
    version: '6.7.2',
    organization_name: 'ETH Zurich',
    country: 'CH',
    description: 'ETH research computing infrastructure for academic projects.',
    logo_url: null,
    admin_email: 'support@cloud.ethz.ch',
    capabilities: ['remote_customer', 'shared_offerings'],
    tags: ['research', 'academia', 'cloud'],
    status: 'active',
    connection_status: 'online',
    last_seen: '2024-06-15T14:28:00Z',
    tos_accepted: true,
    offering_count: 28,
    customer_count: 85,
    project_count: 210,
    registered_at: '2024-02-01T08:00:00Z',
    joined_at: '2024-02-01T09:00:00Z',
  },
  {
    id: 'inst-003',
    federation_id: 'fed-001',
    name: 'DESY Cloud Services',
    api_url: 'https://cloud.desy.de/api',
    homepage_url: 'https://cloud.desy.de',
    uuid: 'c3d4e5f6-a7b8-9012-cdef-345678901234',
    version: '6.8.0',
    organization_name: 'DESY',
    country: 'DE',
    description: 'DESY research infrastructure for photon science and particle physics.',
    logo_url: null,
    admin_email: 'cloud@desy.de',
    capabilities: ['remote_customer', 'shared_offerings', 'usage_reporting'],
    tags: ['physics', 'photon-science', 'hpc'],
    status: 'active',
    connection_status: 'degraded',
    last_seen: '2024-06-15T14:25:00Z',
    tos_accepted: true,
    offering_count: 32,
    customer_count: 65,
    project_count: 180,
    registered_at: '2024-02-15T09:00:00Z',
    joined_at: '2024-02-15T10:00:00Z',
  },
  {
    id: 'inst-004',
    federation_id: 'fed-001',
    name: 'CNRS Computing Grid',
    api_url: 'https://compute.cnrs.fr/api',
    homepage_url: 'https://compute.cnrs.fr',
    uuid: 'd4e5f6a7-b8c9-0123-def4-567890123456',
    version: '6.6.5',
    organization_name: 'CNRS',
    country: 'FR',
    description: 'French national research computing grid operated by CNRS.',
    logo_url: null,
    admin_email: 'grid@cnrs.fr',
    capabilities: ['remote_customer', 'usage_reporting'],
    tags: ['grid', 'research', 'france'],
    status: 'active',
    connection_status: 'offline',
    last_seen: '2024-06-15T10:00:00Z',
    tos_accepted: true,
    offering_count: 18,
    customer_count: 95,
    project_count: 220,
    registered_at: '2024-03-01T10:00:00Z',
    joined_at: '2024-03-01T11:00:00Z',
  },
  {
    id: 'inst-005',
    federation_id: 'fed-001',
    name: 'Max Planck Cloud',
    api_url: 'https://cloud.mpg.de/api',
    homepage_url: 'https://cloud.mpg.de',
    uuid: 'e5f6a7b8-c9d0-1234-ef56-789012345678',
    version: '6.7.8',
    organization_name: 'Max Planck Society',
    country: 'DE',
    description: 'Max Planck computing cloud for fundamental research.',
    logo_url: null,
    admin_email: 'cloud-team@mpg.de',
    capabilities: ['remote_customer', 'shared_offerings'],
    tags: ['research', 'fundamental-science'],
    status: 'pending',
    connection_status: 'unknown',
    last_seen: null,
    tos_accepted: false,
    offering_count: 0,
    customer_count: 0,
    project_count: 0,
    registered_at: '2024-06-10T14:00:00Z',
    joined_at: null,
  },
];

// Sample connections
export const mockConnections: FederationConnection[] = [
  {
    id: 'conn-001',
    federation_id: 'fed-001',
    source_instance_id: 'inst-001',
    target_instance_id: 'inst-002',
    connection_type: 'remote_customer',
    state: 'active',
    created_at: '2024-02-01T10:00:00Z',
    established_at: '2024-02-01T10:05:00Z',
    last_activity: '2024-06-15T14:20:00Z',
    error_count: 0,
  },
  {
    id: 'conn-002',
    federation_id: 'fed-001',
    source_instance_id: 'inst-001',
    target_instance_id: 'inst-003',
    connection_type: 'shared_offering',
    state: 'active',
    created_at: '2024-02-15T09:00:00Z',
    established_at: '2024-02-15T09:10:00Z',
    last_activity: '2024-06-15T14:15:00Z',
    error_count: 0,
  },
  {
    id: 'conn-003',
    federation_id: 'fed-001',
    source_instance_id: 'inst-002',
    target_instance_id: 'inst-003',
    connection_type: 'usage_sync',
    state: 'active',
    created_at: '2024-03-01T11:00:00Z',
    established_at: '2024-03-01T11:02:00Z',
    last_activity: '2024-06-15T14:00:00Z',
    error_count: 1,
  },
  {
    id: 'conn-004',
    federation_id: 'fed-001',
    source_instance_id: 'inst-003',
    target_instance_id: 'inst-004',
    connection_type: 'remote_customer',
    state: 'failed',
    created_at: '2024-04-01T08:00:00Z',
    established_at: '2024-04-01T08:05:00Z',
    last_activity: '2024-06-15T10:00:00Z',
    error_count: 5,
  },
  {
    id: 'conn-005',
    federation_id: 'fed-001',
    source_instance_id: 'inst-001',
    target_instance_id: 'inst-004',
    connection_type: 'shared_offering',
    state: 'pending',
    created_at: '2024-06-14T16:00:00Z',
    established_at: null,
    last_activity: null,
    error_count: 0,
  },
];

// Sample transactions
export const mockTransactions: FederationTransaction[] = [
  {
    id: 'tx-001',
    federation_id: 'fed-001',
    source_instance_id: 'inst-001',
    target_instance_id: 'inst-002',
    transaction_type: 'customer_created',
    status: 'completed',
    created_at: '2024-06-15T14:20:00Z',
    completed_at: '2024-06-15T14:20:05Z',
    duration_ms: 5000,
    error_message: null,
  },
  {
    id: 'tx-002',
    federation_id: 'fed-001',
    source_instance_id: 'inst-002',
    target_instance_id: 'inst-003',
    transaction_type: 'usage_reported',
    status: 'completed',
    created_at: '2024-06-15T14:15:00Z',
    completed_at: '2024-06-15T14:15:02Z',
    duration_ms: 2000,
    error_message: null,
  },
  {
    id: 'tx-003',
    federation_id: 'fed-001',
    source_instance_id: 'inst-001',
    target_instance_id: 'inst-003',
    transaction_type: 'order_created',
    status: 'in_progress',
    created_at: '2024-06-15T14:30:00Z',
    completed_at: null,
    duration_ms: null,
    error_message: null,
  },
  {
    id: 'tx-004',
    federation_id: 'fed-001',
    source_instance_id: 'inst-003',
    target_instance_id: 'inst-004',
    transaction_type: 'sync_failed',
    status: 'failed',
    created_at: '2024-06-15T10:00:00Z',
    completed_at: '2024-06-15T10:00:30Z',
    duration_ms: 30000,
    error_message: 'Connection timeout: Unable to reach target instance',
  },
  {
    id: 'tx-005',
    federation_id: 'fed-001',
    source_instance_id: 'inst-001',
    target_instance_id: null,
    transaction_type: 'health_check',
    status: 'completed',
    created_at: '2024-06-15T14:25:00Z',
    completed_at: '2024-06-15T14:25:01Z',
    duration_ms: 1000,
    error_message: null,
  },
];

// Sample alerts
export const mockAlerts: FederationAlert[] = [
  {
    id: 'alert-001',
    federation_id: 'fed-001',
    instance_id: 'inst-004',
    severity: 'error',
    status: 'active',
    alert_type: 'instance_offline',
    title: "Instance 'CNRS Computing Grid' is offline",
    description: 'The Waldur instance at https://compute.cnrs.fr/api is not responding. Last error: Connection timeout after 30 seconds.',
    created_at: '2024-06-15T10:05:00Z',
    acknowledged_at: null,
    resolved_at: null,
  },
  {
    id: 'alert-002',
    federation_id: 'fed-001',
    instance_id: 'inst-003',
    severity: 'warning',
    status: 'active',
    alert_type: 'instance_degraded',
    title: "Instance 'DESY Cloud Services' is experiencing high latency",
    description: 'Response times have exceeded 5 seconds. Average response time: 6.2 seconds over the last 15 minutes.',
    created_at: '2024-06-15T13:45:00Z',
    acknowledged_at: null,
    resolved_at: null,
  },
  {
    id: 'alert-003',
    federation_id: 'fed-001',
    instance_id: null,
    severity: 'warning',
    status: 'acknowledged',
    alert_type: 'connection_failed',
    title: 'Connection between DESY and CNRS has failed',
    description: 'The connection has failed after 5 consecutive errors. Last error: Target instance unreachable.',
    created_at: '2024-06-15T10:10:00Z',
    acknowledged_at: '2024-06-15T10:30:00Z',
    resolved_at: null,
  },
  {
    id: 'alert-004',
    federation_id: 'fed-001',
    instance_id: 'inst-002',
    severity: 'info',
    status: 'resolved',
    alert_type: 'tos_update',
    title: 'Terms of Service updated',
    description: 'The federation Terms of Service has been updated to version 1.0. Instance administrators should review the changes.',
    created_at: '2024-06-01T08:00:00Z',
    acknowledged_at: '2024-06-01T09:00:00Z',
    resolved_at: '2024-06-02T10:00:00Z',
  },
];

// Dashboard stats
export const mockDashboardStats: Record<string, DashboardStats> = {
  'fed-001': {
    federation: {
      id: 'fed-001',
      name: 'European Research Cloud Federation',
      slug: 'ercf',
      status: 'active',
    },
    instances: {
      total: 5,
      active: 4,
      online: 2,
      offline: 1,
      degraded: 1,
    },
    connections: {
      total: 5,
      active: 3,
      pending: 1,
      failed: 1,
    },
    transactions_24h: {
      total: 156,
      completed: 148,
      failed: 5,
      in_progress: 3,
    },
    active_alerts: {
      info: 0,
      warning: 2,
      error: 1,
      critical: 0,
    },
  },
  'fed-002': {
    federation: {
      id: 'fed-002',
      name: 'Nordic HPC Alliance',
      slug: 'nhpca',
      status: 'active',
    },
    instances: {
      total: 3,
      active: 3,
      online: 3,
      offline: 0,
      degraded: 0,
    },
    connections: {
      total: 4,
      active: 4,
      pending: 0,
      failed: 0,
    },
    transactions_24h: {
      total: 89,
      completed: 87,
      failed: 1,
      in_progress: 1,
    },
    active_alerts: {
      info: 1,
      warning: 0,
      error: 0,
      critical: 0,
    },
  },
};

// Helper to simulate API delay
export const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

// Get instances for a federation
export const getMockInstances = (federationId: string) =>
  mockInstances.filter(i => i.federation_id === federationId);

// Get connections for a federation
export const getMockConnections = (federationId: string) =>
  mockConnections.filter(c => c.federation_id === federationId);

// Get transactions for a federation
export const getMockTransactions = (federationId: string) =>
  mockTransactions.filter(t => t.federation_id === federationId);

// Get alerts for a federation
export const getMockAlerts = (federationId: string) =>
  mockAlerts.filter(a => a.federation_id === federationId);
